# development:
#   adapter: sqlite3
#   database: db/test.sqlite3
#   pool: 5
#   timeout: 5000

# test: &test
#   adapter: sqlite3
#   database: db/test.sqlite3
#   pool: 5
#   timeout: 5000

# production:
#   adapter: sqlite3
#   database: db/test.sqlite3
#   pool: 5
#   timeout: 5000

# staging:
#   adapter: sqlite3
#   database: db/test.sqlite3
#   pool: 5
#   timeout: 5000

development:
  adapter: postgresql
  database: beacon_production
  username: beacon
  password: beacon
  host: localhost
  reconnect: true

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: beacon_production
  username: beacon
  password: beacon
  host: localhost
  reconnect: true

staging:
  adapter: postgresql
  database: beacon_production
  username: beacon
  password: beacon
  host: 192.168.1.51
  reconnect: true
